spring:
       datasource:
                  url: jdbc:mysql://localhost/entrevista_test?serverTimezone=UTC&useLegacyDatetimeCode=false"
                  username: root
                  password:
       jpa:
                  show-sql: false 
                  hibernate:
                            ddl-auto: update 
                  properties:
                            hibernate:
                                     dialect: org.hibernate.dialect.MySQL5Dialect


